name: Deploy to Google Play Store

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17' # or your java version
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE_FILE }}" > keystore.jks.base64
          base64 --decode keystore.jks.base64 > ./app/keystore.jks

      - name: Assemble Release Build
        run: ./gradlew assembleRelease

      - name: Sign Release APK
        run: ./gradlew signReleaseApk

      - name: Upload to Play Store
        uses: r0adkll/upload-google-play@v1.0.25
        with:
          serviceAccountJsonPlainText: ${{ secrets.PLAY_STORE_CREDENTIALS }}
          packageName: com.mmk.webrtcfirebasevideocall
          releaseFiles: app/build/outputs/apk/release/WebRTCFirebaseVideoCall.apk
          track: internal # Change to production once you are ready
