name: Deploy Android APK to Firebase App Distribution

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android Build Tools
        run: sdkmanager "build-tools;33.0.2"

      - name: Set BUILD_TOOLS_VERSION to 33.0.2
        run: echo "BUILD_TOOLS_VERSION=33.0.2" >> $GITHUB_ENV

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Release APK
        run: ./gradlew assembleRelease

      - name: Debug Keystore
        run: |
          echo "${{ secrets.SIGNING_KEY }}" | base64 --decode > debug.jks
          keytool -list -v -keystore debug.jks \
            -storepass "MMM@123" \
            -alias "mmm"
        shell: bash
        if: always()  # Runs even if previous steps fail

      - name: Sign the APK
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: ${{ env.BUILD_TOOLS_VERSION }}
          KEYSTORE_TYPE: PKCS12 # or PKCS12 depending on your key

      - name: Upload APK to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          token: ${{ secrets.FIREBASE_TOKEN }}
          groups: testers
          file: app/build/outputs/apk/release/app-release-signed.apk
